#!/bin/csh -f
#####################################################################
# Copyright 2015 Edwin Z. Crues
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#####################################################################


set rti_lib_dir = ../Environment/lib
set jat_lib_dir = ../Environment/jat/lib
set env_lib_dir = ../Environment/lib

if ( $?RTI_VENDOR ) then
   if ( $RTI_VENDOR =~ 'Mak*' ) then
      if ( $?RTI_HOME ) then
         setenv LD_LIBRARY_PATH ${RTI_HOME}/lib/java:${RTI_HOME}/lib
      else
         echo "If you are using the Mak RTI the RTI_HOME evironment variable must be set."
         exit 1
      endif
   endif
else
   echo "The RTI_VENDOR environment variable is not set."
   echo "The assumption is that you are running with Pitch."
endif

java -cp .:$env_lib_dir/Environment.jar:$rti_lib_dir/rti1516e.jar:$env_lib_dir/jargs.jar:$jat_lib_dir/jatcore.jar:$jat_lib_dir/jatcoreNOSA.jar:./lib/AitkenBasin.jar see.smackdown.aitken_basin.AitkenBasin $argv

